### ISSUE TITLE
jovo alexa skill deployement issue

### ISSUE THREAD

**Issue by GAjayKumar** [jovotech/jovo-framework-nodejs#155]
Hi 

iam getting an issue while deploying jovo alexa skill.

please refer below error 

PS C:\Users\user> jovo deploy

   > Deploying Alexa Skill
     x Creating Alexa Skill project for ASK profile default
       -> Unexpected end of JSON input
       Deploying Interaction Model, waiting for build

Unexpected end of JSON input

Regards,
Ajay

**Comment by jankoenig** [comment]
Hi @GAjayKumar, as discussed in the other thread, was this resolved by creating a new project?

**Comment by GAjayKumar** [comment]
i tried with creating new project and followed the issue #105 though issue persists.

**Comment by jankoenig** [comment]
Which language are you using?

**Comment by csaligram** [comment]
Is this resolved? Even I am getting this error when I deploy.
❯ Deploying Alexa Skill 
     ✖ Creating Alexa Skill project for ASK profile default
       -> Unexpected end of JSON input
       Deploying Interaction Model, waiting for build

Unexpected end of JSON input

**Comment by jankoenig** [comment]
Hi there. Which version of ASK CLI are you using? It's used for deployment, and they changed a few things recently. `ask -v`. I'm using `1.5.1` and it works for me. 

Which version of the Jovo CLI are you using?

**Comment by csaligram** [comment]
My versions
ask - 1.5.1
jovo-cli 1.2.11

**Comment by jankoenig** [comment]
Can you paste the content of your `skill.json` please? It's in `platforms/alexaSkill`

**Comment by csaligram** [comment]
Here is platforms/alexaSkill/skill.json.
{
	"manifest": {
		"publishingInformation": {
			"locales": {
				"en-US": {
					"summary": "Sample Short Description",
					"examplePhrases": [
						"Alexa open hello world"
					],
					"name": "helloWorld",
					"description": "Sample Full Description"
				}
			},
			"isAvailableWorldwide": true,
			"testingInstructions": "Sample Testing Instructions.",
			"category": "EDUCATION_AND_REFERENCE",
			"distributionCountries": []
		},
		"apis": {
			"custom": {
				"endpoint": {
					"sslCertificateType": "Wildcard",
					"uri": "https://webhook.jovo.cloud/425742e6-40ee-473c-b258-147a88ffce17"
				}
			}
		},
		"manifestVersion": "1.0"
	}
}

**Comment by csaligram** [comment]
How does Jovo connect with my Alexa developer account? I haven't set up any skill in Alexa Developer Console. I thought "jovo deploy" would do that automatically

**Comment by csaligram** [comment]
Thank you. I resolved this. Basically, I had not created an AWS security profile. After doing it through "aws configure" and doing "ask init" I was able to successfully do "jovo deploy".
